### PR TITLE
Outputs vectors in JSON format.

### PR DESCRIPTION
**Pull request by armfazh**
Sometimes is easier to parse a JSON file.

### CODE REVIEW

**Review by meichlseder — CHANGES_REQUESTED** [review]
Thanks for your proposal!

The current code follows the requirements of the NIST call ([description](https://csrc.nist.gov/CSRC/media/Projects/Lightweight-Cryptography/documents/final-lwc-submission-requirements-august2018.pdf), [code](https://csrc.nist.gov/CSRC/media/Projects/Lightweight-Cryptography/documents/TestVectorGen.zip)), so we cannot change the format.

What we could do is support a `json` option/flag so that the user can choose to either print the original pure text format or the json format, if you'd be willing to adapt your PR accordingly. Thanks!

**Comment by armfazh** [comment]
Makes sense, I will come back to update my code later.

**Comment by armfazh** [comment]
Current code produces both Text and JSON formats.

**Comment by meichlseder** [comment]
Thank you!

**Pull request merged**
